# Generated by Django 5.1.1 on 2024-09-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Event date')),
                ('event', models.CharField(choices=[('S', 'Sightseeing'), ('E', 'Entertainment'), ('R', 'Relaxation'), ('A', 'Adventure')], default='S', max_length=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trip')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
