# Generated by Django 5.1.1 on 2024-09-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tripevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tripevents',
            field=models.ManyToManyField(related_name='trips', to='main_app.tripevent'),
        ),
    ]
