# Generated by Django 5.1.1 on 2024-09-11 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_trip_tripevents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='end_date',
            field=models.DateField(verbose_name='JournalEntry date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='start_date',
            field=models.DateField(verbose_name='JournalEntry date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trip')),
            ],
        ),
    ]
