# Generated by Django 5.1.1 on 2024-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripevent',
            name='event',
            field=models.CharField(choices=[('S', 'Sightseeing'), ('E', 'Entertainment'), ('R', 'Relaxation'), ('A', 'Adventure'), ('H', 'Hiking'), ('W', 'Wedding'), ('S', 'Swimming')], default='S', max_length=1),
        ),
    ]
